"""
Implements the main command line interface of the E3 data crawler
"""

import argparse
import logging
import os
import string
from typing import Optional

import dotenv
import yaml

logger = logging.getLogger(__name__)


def main(argv=None, prog=None):
    """
    Parses the commandline arguments, reads the configuration and starts the main program flow

    :param argv: An optional argument vector that can be supplied for testing purposes
    :param prog: An optional program name. Otherwise the first element in the argument vector will be used
    """

    logging.basicConfig(format="%(asctime)s %(name)s %(levelname)s: %(message)s", level=logging.DEBUG)

    parser = argparse.ArgumentParser(prog=prog, description="Periodically fetches the data sources")
    parser.add_argument("--config_file", metavar="CONF", default="data_crawler.yaml",
                        help="The main YAML configuration describing the data sources")
    parser.add_argument("--env", metavar="ENV_FILE", default=None,
                        help="An environment file that specifies the variables to load")
    args = parser.parse_args(args=argv)

    load_env_file(args.env)
    logger.debug("Parse main YAML configuration file '%s'", args.config_file)
    config = load_config(args.config_file)

    pass  # TODO: Implement the main program flow


def load_env_file(env_file: Optional[str]) -> None:
    """
    Populates the environment vairables by elements stored in the .env file

    :param env_file: The path of the .env file or None, in case nothing should be changed
    """

    if env_file is not None:
        logger.debug("Load environment file '%s'", env_file)
        dotenv.load_dotenv(env_file)


def load_config(config_file: str) -> dict:
    """
    Parses the YAML configuration, preprocesses it and returns the resulting structure of dictionaries
    :param config_file: The path of the main configuration file
    :return: The obtained configuration as a structure of nested dicts as generated by the YAML loader
    """

    config_file = os.path.abspath(config_file)
    if not os.path.isfile(config_file):
        raise FileNotFoundError(f"The main configuration file '{config_file}' is not found")

    yaml.add_constructor("!env-template", _load_substitute_env)

    with open(config_file, "r") as f:
        config = yaml.load(f, Loader=yaml.Loader)

    if not config.get("version", 1) == 1:
        raise SyntaxError("Invalid configuration version. Only version 1 is supported.")

    return config


def _load_substitute_env(loader, node):
    """Loads the YAML node by substituting environment variables using Python template syntax"""

    template_str = loader.construct_scalar(node)
    template = string.Template(template_str)
    return template.substitute(**os.environ)
